name: CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: ESLint check
        run: yarn lint

      - name: Run the tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Build
        run: yarn build

      - name: Generate static files
        run: yarn export

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
